repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
  #  - repo: https://github.com/pre-commit/mirrors-prettier
  #    rev: "" # Use the sha or tag you want to point at
  #    hooks:
  #      - id: prettier
  - repo: https://github.com/ambv/black
    rev: "23.3.0"
    hooks:
      - id: black
  - repo: https://github.com/lovesegfault/beautysh
    rev: "v6.2.1"
    hooks:
      - id: beautysh
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.32.0"
    hooks:
      - id: yamllint

#  - repo: local
#    hooks:
#        - id: isort
#          name: Isort
#          entry: isort --check --diff .
#          language: system
#          pass_filenames: false
#          #            - id: mypy
#          #              name: Mypy
#          #              entry: mypy .
#          #              language: system
#          #              pass_filenames: false
#        - id: black
#          name: Black
#          entry: black --check .
#          language: system
#          pass_filenames: false
